name: 'SunSpec Models'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: 'Build with Java 11'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout sourcecode'
      uses: actions/checkout@v3

    - name: 'Cache Local Maven Repository'
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: 'Setup: Install JDK 11'
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: |
          11

    - name: Build
      run: mvn -B install
